/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}', './index.html'],
  corePlugins: { preflight: false }, // prevent clash with existing App.css
  theme: {
    extend: {
      colors: {
        // Editorial palette used across Test / Results / IdealPartner redesigns
        primary:            '#051125',
        'primary-container':'#1b263b',
        'primary-fixed':    '#d7e2ff',
        'primary-fixed-dim':'#bbc6e2',
        'on-primary':       '#ffffff',
        'on-primary-container':'#828da7',
        secondary:          '#6d4ea2',
        'secondary-container':'#c5a3ff',
        'secondary-fixed':  '#ebdcff',
        'secondary-fixed-dim':'#d4bbff',
        'on-secondary':     '#ffffff',
        'on-secondary-container':'#533487',
        'on-secondary-fixed':'#270058',
        'on-secondary-fixed-variant':'#543589',
        tertiary:           '#2c0011',
        'tertiary-container':'#520025',
        'tertiary-fixed':   '#ffd9e1',
        'tertiary-fixed-dim':'#ffb1c5',
        'on-tertiary':      '#ffffff',
        'on-tertiary-container':'#e85c8c',
        'on-tertiary-fixed':'#3f001b',
        'on-tertiary-fixed-variant':'#8b0e45',
        surface:                      '#f8f9fa',
        'surface-bright':             '#f8f9fa',
        'surface-dim':                '#d9dadb',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f3f4f5',
        'surface-container':          '#edeeef',
        'surface-container-high':     '#e7e8e9',
        'surface-container-highest':  '#e1e3e4',
        'surface-variant':            '#e1e3e4',
        'inverse-surface':            '#2e3132',
        'inverse-on-surface':         '#f0f1f2',
        'on-surface':                 '#191c1d',
        'on-surface-variant':         '#45474d',
        'on-background':              '#191c1d',
        background:                   '#f8f9fa',
        outline:                      '#75777d',
        'outline-variant':            '#c5c6cd',
        error:                        '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:  '0.5rem',
        xl:  '0.75rem',
        full:'9999px',
      },
      boxShadow: {
        'editorial':     '0px 12px 32px rgba(5,17,37,0.06)',
        'editorial-lg':  '0px 12px 32px rgba(5,17,37,0.15)',
        'bottom-nav':    '0px -12px 32px rgba(5,17,37,0.04)',
      },
    },
  },
  plugins: [],
}
